### ISSUE TITLE
Question about multiple site tracking

### ISSUE THREAD

**Issue by beatelite** [proximedia/angular-piwik#2]
I noticed your docs say "you can't track multiple sites for the moment"

What exactly do you mean by that?

I have an multi-tenant angular app that should gather info about their site via their piwik tracking code and return them visuals in their angular dashboard via your directive. Since, technically, there will be multiple sites tracked, will this affect my use of this directive?

**Comment by mrjoops** [comment]
This is about tracking, not about reporting.

Actually you can't put more than one tracker per page for the moment (I mean one pxm-piwik directive).

This limitation doesn't apply to reporting, so you can always specify a different idSite when you use $piwik.call() or $piwik.widget().

Do I answer your question ?

**Comment by beatelite** [comment]
Yes, that definitely answers my question. Close this baby out and thanks for putting this together. I'm already getting a lot of use out of it!

Btw, are you using any custom charts for this directive? If so, have any recommendations on the best-easiest to set up and use with it?

**Comment by mrjoops** [comment]
Well I'm using [Google Charts](https://developers.google.com/chart/) quite successfully.
